### ISSUE TITLE
Multiple Systems Error

### ISSUE THREAD

**Issue by markus99** [hikirsch/htd_mc-home-assistant#1]
Trying to configure multiple systems and receiving an error:

```
Invalid config for [htd_mc]: expected a dictionary for dictionary value @ data['htd_mc']. Got [OrderedDict([('host', '192.168.86.61'), ('port', 10006), ('zones', ['Outside - Couch', 'Outside - Fireplace', 'Outside - Rocks', 'Kitchen', 'Dining Room', 'Master Bathroom']), ('sources', ['Apple', 'Up - Chromecast', 'Dn - Chromecast', 'TV - Outside', 'TV - Family Rm'])]), OrderedDict([('host', '192.168.86.231'), ('port', 10006), ('zones', ['Pool Table Room', "Aubrey's Room", "Jonas' Room", '-unused-', 'Office', 'Workout Room']), ('sources', ['Pool Table TV', 'Up - Chromecast', 'Dn - Chromec.... (See /config/configuration.yaml, line 276).
```

Configuration.yaml:
```
htd_mc:
  - host: 192.168.xxx.xxx
    port: 10006
    zones:
      - Zone 1
      - Zone 2
    sources:
      - Source 1
      - Source 2
  - host: 192.168.xxx.yyy
    port: 10006
    zones:
      - Zone 1a
      - Zone 2a
    sources:
      - Source 1a
      - Source 2a
```
